name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Build and package
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: pip install pyinstaller &&
          pip config set global.target ./site-packages &&
          pip install -r requirements.txt &&
          pyinstaller
          --hidden-import "PyQt5"
          --hidden-import "PyQt5.QtWebEngineWidgets" 
          -p .
          -p ./site-packages/PyQt5/
          -p ./site-packages/PyQt5/Qt/
          -p ./site-packages/PyQt5/Qt5/
          -p ./site-packages/geatpy/core/
          -p ./site-packages/geatpy/
          -p ./site-packages/geatpy/operators/
          -p ./site-packages/geatpy/templates/moeas/
          -p ./site-packages/geatpy/templates/moeas/awGA/
          -p ./site-packages/geatpy/templates/moeas/moead/
          -p ./site-packages/geatpy/templates/moeas/nsga2/
          -p ./site-packages/geatpy/templates/moeas/nsga3/
          -p ./site-packages/geatpy/templates/moeas/pps/
          -p ./site-packages/geatpy/templates/moeas/rvea/
          -p ./site-packages/geatpy/templates/soeas/
          gui/MyMainWindows.py &&
          Xcopy .\site-packages\pyecharts\render\templates .\dist\MyMainWindows\templates\ /E /H /C /I &&
          Xcopy .\gui\templates\* .\dist\MyMainWindows\ /E /H /C /I
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/



#pyinstaller -p . gui/myMainWindows.py -p D:/anaconda3/Lib/site-packages/geatpy/
#templates/moeas/awGA/ -p D:/anaconda3/Lib/site-packages/geatpy/templates/moeas/moead/  -p D:/anaconda3/Lib/site-p
#ackages/geatpy/templates/moeas/nsga2/ -p D:/anaconda3/Lib/site-packages/geatpy/templates/moeas/nsga3/  -p D:/anac
#onda3/Lib/site-packages/geatpy/templates/moeas/pps/ -p D:/anaconda3/Lib/site-packages/geatpy/templates/moeas/rvea
#/ -p D:/anaconda3/Lib/site-packages/geatpy/templates/soeas/
