name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Build and package
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: pip config set global.target ./site-packages && \
          pip install -r requirements.txt && \
          pip install pyinstaller && \
          pyinstaller -F -p . -p ./site-packages/ gui/MyMainWindows.py
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./*.exe
