name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "./site-packages"
          key: ${{ runner.os }}-packages
      - name: Build and package
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: pip install pyinstaller &&
          pip config set global.target ./site-packages &&
          pip install -r requirements.txt &&
          pyinstaller --hidden-import "PyQtWebEngine" -p . -p ./site-packages/geatpy/core/ 
          -p ./site-packages/PyQt5/ 
          -p ./site-packages/PyQt5/Qt5/
          -p ./site-packages/ 
          -p ./site-packages/geatpy/ 
          -p ./site-packages/geatpy/operators/
          -p ./site-packages/geatpy/templates/moeas/
          -p ./site-packages/geatpy/templates/moeas/awGA/
          -p ./site-packages/geatpy/templates/moeas/moead/
          -p ./site-packages/geatpy/templates/moeas/nsga2/
          -p ./site-packages/geatpy/templates/moeas/nsga3/
          -p ./site-packages/geatpy/templates/moeas/pps/
          -p ./site-packages/geatpy/templates/moeas/rvea/
          -p ./site-packages/geatpy/templates/soeas/ 
          gui/MyMainWindows.py
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/
